### ISSUE TITLE
`CPUDevice` doesn't preserve structure of `ComponentArray`

### ISSUE THREAD

**Issue by sgstepaniants** [LuxDL/LuxDeviceUtils.jl#10]
When I run the following code (with dev simply set to cpu)
```
cd(@__DIR__)

using Pkg
Pkg.activate(".")
Pkg.instantiate()

using Lux
using ComponentArrays
using Random

model = Dense(1, 1)

rng = Random.default_rng()
Random.seed!(rng, 0)

ps, _ = Lux.setup(rng, model)
dev = gpu_device()
ps = ps |> ComponentArray |> dev
```

The final parameter vector ps is simply a Vector{Float32} which is wrong.

**Comment by avik-pal** [comment]
More minimal version

```julia
using LuxDeviceUtils, ComponentArrays, Random
dev = gpu_device()
ps = (; weight=randn(10, 1), bias=randn(1))
ps |> ComponentArray |> dev
```

Seems somewhere `CPUDevice` is messing up the conversion.

(Sidenote: `CUDADevice` is working properly, `gpu_device` fails to detect that since `LuxCUDA` is not loaded)
