### ISSUE TITLE
Support RecursiveArrayTools

### ISSUE THREAD

**Issue by avik-pal** [LuxDL/LuxDeviceUtils.jl#22]
Since RAT v0.3 the AbstractVectorOfArrays is no longer an AbstractArray which broke our dispatches via functor, but this should be easy to handle.

**Comment by avik-pal** [comment]
@ChrisRackauckas @AayushSabharwal should I handle this here as a special case extension. Or should we setup those types to be functors?

**Comment by AayushSabharwal** [comment]
I'm not sure what sort of dispatches are required here. Could you give an example? If they're not generally applicable (and only really matter for Lux), I'd argue they should be handled as an extension here. This allows RAT to provide the types and the interface, and leaves the required specializations to users of the library

**Comment by ChrisRackauckas** [comment]
Yeah handle that here
