### ISSUE TITLE
`device(NN::AbstractExplicitLayer)` doesn't need to error

### ISSUE THREAD

**Issue by vpuri3** [LuxDL/LuxDeviceUtils.jl#24]
https://github.com/LuxDL/LuxDeviceUtils.jl/blob/d98c090b87da353b6b1e2fbe3d057bbfa1f988e2/src/LuxDeviceUtils.jl#L245-L247

I agree `device(NN)` isn't necessary but it doesn't need to error. Simply returning `NN` won't hurt anything downstream. Adding a `@warn "..." maxlog = 1` would do

**Comment by avik-pal** [comment]
I would be okay with making this change now. It was added initially because there were quite a few bug reports where users just applied the device on the model, but now that doesn't happen now.

Can you make a PR?
